// agent/core/agent-loop.js

// Import necessary modules from other parts of the agent.
const { generateResponse } = require('./llm-client');
const { appendMemory, saveMemory } = require('../memory/memory-store'); 
// Import our new intent extractor function.
const { extractIntentAndEntities } = require('./intent-extractor');
const { fetchStockPrice } = require('../data_sources/finance_api');

/**
 * Executes a single cycle of the agent's operation. This now includes intent extraction.
 * 
 * @param {string} userInput - The text input provided by the user.
 * @returns {Promise<string>} The text response generated by the LLM for the user.
 * @throws {Error} If any step in the cycle fails.
 */
async function runAgentCycle(userInput) {
  // Basic validation for user input.
  if (!userInput || typeof userInput.trim() !== 'string' || userInput.trim() === '') {
    throw new Error("Invalid user input provided for agent cycle. Input cannot be empty.");
  }

  try {
    // First, extract intent from the user's initial query to see if it's a data request
    const { thematic_scope, entities, event_type } = await extractIntentAndEntities(userInput, ""); // Pass empty response for initial check

    let llmResponse;
    let context = {}; // To hold any fetched data

    // 2. NEW STEP: Check if the request is for data that we can fetch with a tool.
    if (event_type === 'data_request' && entities.some(e => e.type === 'STOCK_TICKER')) {
      console.log('Agent loop: Detected a data request. Attempting to use tools...');
      const tickerEntity = entities.find(e => e.type === 'STOCK_TICKER');
      if (tickerEntity) {
        // Use the new finance_api tool
        const price = await fetchStockPrice(tickerEntity.value);
        if (price !== null) {
          context.price = price;
          // Create an enhanced prompt for the LLM that includes the fetched data
          const enhancedPrompt = `The user asked: "${userInput}". Using the following data that I found: The price of ${tickerEntity.value} is $${price}. Please formulate a natural language response.`;
          llmResponse = await generateResponse(enhancedPrompt);
        } else {
          // If fetching fails, fall back to the normal response generation
          llmResponse = await generateResponse(userInput);
        }
      } else {
        llmResponse = await generateResponse(userInput);
      }
    } else {
      // 1. If not a data request, generate the main response from the LLM directly.
      console.log(`Agent loop: Requesting LLM response for: "${userInput}"`);
      llmResponse = await generateResponse(userInput);
    }
    
    console.log(`Agent loop: Received response from LLM.`);

    // 3. Prepare the data for the new memory entry, now with dynamic scope and entities.
    const memoryEntryData = {
      user_input: userInput,
      llm_response: llmResponse,
      thematic_scope: thematic_scope, // Use the dynamically extracted scope
      event_type: event_type,          // Use the dynamically extracted event type
      entities: entities,              // Use the dynamically extracted entities
      context: context                 // Store the fetched data in memory
    };

    // 4. Append the new, richer memory entry to the in-memory store.
    const addedEntry = appendMemory(memoryEntryData);

    // If appendMemory returns null, it means validation failed.
    if (!addedEntry) {
      throw new Error("Failed to append a valid memory entry. Check logs for details.");
    }

    // 5. Save the entire memory store to disk to persist the changes.
    await saveMemory();

    // 6. Return only the primary LLM response to be displayed in the UI.
    return llmResponse;

  } catch (error) {
    console.error(`Agent Cycle Error: ${error.message}`);
    // Re-throw the error so it can be caught and handled by the entry point (e.g., index.js).
    throw error;
  }
}

// Export the updated runAgentCycle function.
module.exports = {
  runAgentCycle,
};
