// agent/core/agent-loop.js

// Import necessary modules from other parts of the agent.
const { generateResponse } = require('./llm-client');
const { appendMemory, saveMemory } = require('../memory/memory-store'); 
// Import our new intent extractor function.
const { extractIntentAndEntities } = require('./intent-extractor');
// Import the new retriever and the finance API tool
const { retrieveRelevantMemories } = require('../memory/memory-retriever');
const { fetchStockPrice } = require('../data_sources/finance_api');
const { fetchNews } = require('../data_sources/news_api');
const { getCik, fetchCompanyFacts, fetchSubmissionMetadata } = require('../data_sources/sec_api');



/**
 * Executes a single cycle of the agent's operation. This now includes intent extraction.
 * 
 * @param {string} userInput - The text input provided by the user.
 * @returns {Promise<string>} The text response generated by the LLM for the user.
 * @throws {Error} If any step in the cycle fails.
 */
async function runAgentCycle(userInput) {
  // Basic validation for user input.
  if (!userInput || typeof userInput.trim() !== 'string' || userInput.trim() === '') {
    throw new Error("Invalid user input provided for agent cycle. Input cannot be empty.");
  }

  let toolCall = null; // To hold tool call information

  try {
    // 1. Understand Intent: Extract intent from the current query *first* to decide what to do.
    console.log(`Agent loop: Extracting intent from query: "${userInput}"`);
    const initialIntent = await extractIntentAndEntities(userInput, "");

    let llmResponse;
    let contextForMemory = {}; // Holds data fetched from tools, to be saved in memory.
    let augmentedPrompt = userInput; // Default prompt is just the user's input.

    // 2. Decide Action: Prioritize tool use (data_request, news_request, earnings_request, filing_request) over memory retrieval.
    if (initialIntent.event_type === 'data_request' && initialIntent.entities.some(e => e.type === 'STOCK_TICKER')) {
      // --- Tool Use Path: Fetch Stock Price ---
      console.log('Agent loop: Detected a data request for stock price. Using finance tool...');
      const tickerEntity = initialIntent.entities.find(e => e.type === 'STOCK_TICKER');
      if (tickerEntity) {
        const startTime = Date.now();
        const price = await fetchStockPrice(tickerEntity.value);
        const duration = ((Date.now() - startTime) / 1000).toFixed(1);

        if (price !== null) {
          contextForMemory.price = price; // Store fetched data in context for memory.
          augmentedPrompt = `The user asked: "${userInput}". Using the data I found: The live price of ${tickerEntity.value} is $${price}. Formulate a natural language response.`;
          toolCall = {
            toolName: 'Finance API',
            prompt: userInput,
            dataSource: 'Alpha Vantage API', // Assuming this is the source
            duration: duration,
          };
        }
      }
    } else if (initialIntent.event_type === 'news_request' && initialIntent.entities.some(e => e.type === 'STOCK_TICKER')) {
      // --- Tool Use Path: Fetch News ---
      console.log('Agent loop: Detected a news request. Using news tool...');
      const tickerEntity = initialIntent.entities.find(e => e.type === 'STOCK_TICKER');
      if (tickerEntity) {
        let fromDateTime = null;
        let toDateTime = null;

        const fromEntity = initialIntent.entities.find(e => e.type === 'DATE_FROM');
        const toEntity = initialIntent.entities.find(e => e.type === 'DATE_TO');

        if (fromEntity && toEntity) {
          fromDateTime = fromEntity.value;
          toDateTime = toEntity.value;
          console.log(`Agent loop: Fetching news from ${fromDateTime} to ${toDateTime}`);
        } else {
          // Default to the last 24 hours if no specific date range is provided
          const now = new Date();
          const twentyFourHoursAgo = new Date(now.getTime() - (24 * 60 * 60 * 1000));

          const formatDateTime = (date) => {
            return date.toISOString().replace(/[-:]|\..+/g, '').slice(0, 13);
          };

          fromDateTime = formatDateTime(twentyFourHoursAgo);
          toDateTime = formatDateTime(now);
          console.log(`Agent loop: Fetching latest news (last 24 hours)`);
        }
        
        const startTime = Date.now();
        const newsArticles = await fetchNews(tickerEntity.value, { from: fromDateTime, to: toDateTime, limit: 5 });
        const duration = ((Date.now() - startTime) / 1000).toFixed(1);

        if (newsArticles && newsArticles.length > 0) {
          contextForMemory.news = newsArticles;

          toolCall = {
            toolName: 'News API',
            prompt: `What's the latest news on ${tickerEntity.value}?`, // Example prompt
            dataSource: 'Alpha Vantage API',
            duration: duration,
          };

          const formattedNews = newsArticles.map(article => {
            const sentimentScore = parseFloat(article.overall_sentiment_score).toFixed(2);
            return `- ${article.title} (Source: ${article.source}) [Sentiment: ${sentimentScore}]`;
          }).join('\n');

          augmentedPrompt = `
            The user asked: "${userInput}".
            Here are the relevant news headlines I found for ${tickerEntity.value} from ${fromDateTime} to ${toDateTime}.
            Present this list to the user exactly as it is written, without any changes or summarization.

            --- News Headlines ---
            ${formattedNews}
            ---
          `;
        } else {
          augmentedPrompt = `The user asked: "${userInput}". I could not find any news for ${tickerEntity.value} from ${fromDateTime} to ${toDateTime}. Please inform the user.`;
        }
      }
    } else if (initialIntent.event_type === 'earnings_request' && initialIntent.entities.some(e => e.type === 'STOCK_TICKER')) {
      // --- Tool Use Path: Fetch Earnings Data from SEC EDGAR API ---
      console.log('Agent loop: Detected an earnings request. Using SEC EDGAR API...');
      const tickerEntity = initialIntent.entities.find(e => e.type === 'STOCK_TICKER');
      if (tickerEntity) {
        const ticker = tickerEntity.value;
        const startTime = Date.now();
        const cik = await getCik(ticker);
        if (!cik) {
          augmentedPrompt = `The user asked: "${userInput}". I could not find the CIK for ticker ${ticker}. Please inform the user.`;
          llmResponse = await generateResponse(augmentedPrompt);
          return { response: llmResponse, toolCall: null };
        }

        const companyFacts = await fetchCompanyFacts(cik);
        const duration = ((Date.now() - startTime) / 1000).toFixed(1);

        toolCall = {
          toolName: 'Earnings API',
          prompt: userInput,
          dataSource: 'SEC EDGAR API',
          duration: duration,
        };
        
        if (!companyFacts || !companyFacts.facts || !companyFacts.facts['us-gaap']) {
          augmentedPrompt = `The user asked: "${userInput}". I could not retrieve company facts for ${ticker} (CIK: ${cik}). Please inform the user.`;
          llmResponse = await generateResponse(augmentedPrompt);
          return { response: llmResponse, toolCall: toolCall };
        }

        contextForMemory.companyFacts = companyFacts;
        
        // ... (rest of the earnings logic)
      }
    } else if (initialIntent.event_type === 'filing_request' && initialIntent.entities.some(e => e.type === 'STOCK_TICKER')) {
      // --- Tool Use Path: Fetch SEC Filings from SEC EDGAR API ---
      console.log('Agent loop: Detected a filing request. Using SEC EDGAR API...');
      const tickerEntity = initialIntent.entities.find(e => e.type === 'STOCK_TICKER');
      if (tickerEntity) {
          const ticker = tickerEntity.value;
          const startTime = Date.now();
          const cik = await getCik(ticker);
          if (!cik) {
            augmentedPrompt = `The user asked: "${userInput}". I could not find the CIK for ticker ${ticker}. Please inform the user.`;
            llmResponse = await generateResponse(augmentedPrompt);
            return { response: llmResponse, toolCall: null };
          }

          const submissionMetadata = await fetchSubmissionMetadata(cik);
          const duration = ((Date.now() - startTime) / 1000).toFixed(1);

          toolCall = {
            toolName: 'Filing API',
            prompt: userInput,
            dataSource: 'SEC EDGAR API',
            duration: duration,
          };
          
          if (!submissionMetadata || !submissionMetadata.filings || !submissionMetadata.filings.recent) {
            augmentedPrompt = `The user asked: "${userInput}". I could not retrieve submission metadata for ${ticker} (CIK: ${cik}). Please inform the user.`;
            llmResponse = await generateResponse(augmentedPrompt);
            return { response: llmResponse, toolCall: toolCall };
          }

          contextForMemory.submissionMetadata = submissionMetadata;
          
          // ... (rest of the filing logic)
        }
    }

    if (!llmResponse) {
        console.log(`Agent loop: Generating response with final prompt...`);
        llmResponse = await generateResponse(augmentedPrompt);
        console.log(`Agent loop: Received final response from LLM.`);
    }

    const memoryEntryData = {
      user_input: userInput,
      llm_response: llmResponse,
      thematic_scope: initialIntent.thematic_scope,
      event_type: initialIntent.event_type,
      entities: initialIntent.entities,
      context: contextForMemory
    };

    const addedEntry = appendMemory(memoryEntryData);
    if (!addedEntry) {
      throw new Error("Failed to append a valid memory entry. Check logs for details.");
    }
    await saveMemory();

    return { response: llmResponse, toolCall: toolCall };
  } catch (error) {
    console.error(`Agent Cycle Error: ${error.message}`);
    throw error;
  } finally {
    console.log("Agent cycle finished.");
  }
}

// Export the updated runAgentCycle function.
module.exports = {
  runAgentCycle,
};
